-- SC20: per-channel alert delivery rows (email/slack fan-out), dispatched by
-- AlertDeliveryScheduler outside the alert-opening transaction (webhook-relay shape).
CREATE TABLE karyo.alert_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    tenant_id BIGINT NOT NULL,
    alert_id BIGINT NOT NULL,
    channel_key VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_error VARCHAR(1000)
);
CREATE INDEX idx_alert_deliveries_due ON karyo.alert_deliveries (status, next_attempt_at);
