-- V1202__create_system_properties.sql
-- SC16: runtime-editable config store (myWMS SystemProperty behavioral parity;
-- key/context/client-scoped rows; catalog metadata is code-owned, not stored).
CREATE TABLE karyo.system_properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    client_id BIGINT NOT NULL,
    property_key VARCHAR(255) NOT NULL,
    property_context VARCHAR(255),
    property_value VARCHAR(2000),
    description VARCHAR(2000),
    property_group VARCHAR(255),
    CONSTRAINT uq_system_properties UNIQUE NULLS NOT DISTINCT (client_id, property_key, property_context)
);
CREATE INDEX idx_system_properties_client ON karyo.system_properties (client_id);
