-- Client (goods owner) — the entity behind the client_id carried by TenantEntity.
-- Functional contract: docs/functional/inventory-operations.md#1-goods-ownership-and-scope
--
-- No foreign keys reference this table (design D3): the 24 client_id columns span
-- 12 modules, and the modulith rule is IDs-only across module boundaries.
-- Integrity is advisory and reported by GET /api/v1/clients/consistency.

CREATE TABLE karyo.clients (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     INTEGER      NOT NULL DEFAULT 0,
    created     TIMESTAMPTZ  NOT NULL,
    modified    TIMESTAMPTZ  NOT NULL,
    name        VARCHAR(255) NOT NULL,
    number      VARCHAR(64)  NOT NULL,
    code        VARCHAR(64)  NOT NULL DEFAULT '',
    email       VARCHAR(255) NOT NULL DEFAULT '',
    phone       VARCHAR(64)  NOT NULL DEFAULT '',
    fax         VARCHAR(64)  NOT NULL DEFAULT '',
    state       INTEGER      NOT NULL DEFAULT 100
);

CREATE UNIQUE INDEX idx_clients_name   ON karyo.clients (name);
CREATE UNIQUE INDEX idx_clients_number ON karyo.clients (number);

-- Backfill the client_id values already present in live data (design D4).
-- id 0 is the system/ops tenant AND TenantEntity's default; code mirrors the
-- tenant_code JWT claim.
INSERT INTO karyo.clients (id, version, created, modified, name, number, code, state) VALUES
    (0, 0, now(), now(), 'System',             'SYS',    'SYS',    100),
    (1, 0, now(), now(), 'ACME Corporation',   'ACME',   'ACME',   100),
    (2, 0, now(), now(), 'Globex Corporation', 'GLOBEX', 'GLOBEX', 100);

-- Explicit ids above do not advance the identity sequence. Without this, the first
-- generated id is 1 and collides with ACME. Start generated ids at 100.
SELECT setval('karyo.clients_id_seq', 100, false);
