CREATE TABLE karyo.document_templates (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          INTEGER      NOT NULL DEFAULT 0,
    created          TIMESTAMPTZ  NOT NULL,
    modified         TIMESTAMPTZ  NOT NULL,
    client_id        BIGINT       NOT NULL DEFAULT 0,
    template_path    VARCHAR(255) NOT NULL,
    template_version INTEGER      NOT NULL,
    active           BOOLEAN      NOT NULL DEFAULT true,
    content          TEXT         NOT NULL
);
CREATE UNIQUE INDEX idx_document_templates_active_key
    ON karyo.document_templates (client_id, template_path) WHERE active;
CREATE INDEX idx_document_templates_key ON karyo.document_templates (client_id, template_path, template_version DESC);
