CREATE TABLE karyo.documents (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       INTEGER      NOT NULL DEFAULT 0,
    created       TIMESTAMPTZ  NOT NULL,
    modified      TIMESTAMPTZ  NOT NULL,
    client_id     BIGINT       NOT NULL DEFAULT 0,
    entity_type   VARCHAR(64)  NOT NULL,
    entity_id     BIGINT       NOT NULL,
    document_type VARCHAR(64)  NOT NULL,
    file_name     VARCHAR(255) NOT NULL,
    media_type    VARCHAR(64)  NOT NULL,
    size_bytes    INTEGER      NOT NULL,
    content       BYTEA        NOT NULL
);
CREATE INDEX idx_documents_client_entity ON karyo.documents (client_id, entity_type, entity_id);
CREATE INDEX idx_documents_client_created ON karyo.documents (client_id, created DESC);
