ALTER TABLE order_strategies
    ADD COLUMN IF NOT EXISTS prefer_matching  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS complete_handling INT    NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS enforce_lot       BOOLEAN NOT NULL DEFAULT FALSE;
