ALTER TABLE order_strategies
    ADD COLUMN IF NOT EXISTS short_pick_mode    VARCHAR(40) NOT NULL DEFAULT 'FOLLOW_UP_THEN_SUBSTITUTE',
    ADD COLUMN IF NOT EXISTS shortfall_strategy VARCHAR(60) NOT NULL DEFAULT 'PARTIAL_SHIP';
