-- V2__create_sequence_numbers.sql — SC17 FORMATTED_COUNTER state (myWMS sequencenumber parity).
-- Global per name (no client_id): matches legacy UNIQUE(name); unit-load labels are globally unique.
CREATE TABLE karyo.sequence_numbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    name VARCHAR(255) NOT NULL,
    counter BIGINT NOT NULL DEFAULT 0,
    end_counter BIGINT NOT NULL DEFAULT 9999,
    format VARCHAR(255) NOT NULL DEFAULT '%1$04d',
    check_digit_type VARCHAR(32),
    CONSTRAINT uq_sequence_numbers_name UNIQUE (name)
);
