-- V1500: stream_batches (streaming module, Advanced Fulfillment pack). One row per flush/retry tick
-- that did work; feeds GET /api/v1/streaming/status. ID-only references, no FK (house rule).
CREATE TABLE stream_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER NOT NULL DEFAULT 0,
    created TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified TIMESTAMPTZ NOT NULL DEFAULT now(),
    client_id BIGINT NOT NULL,
    order_strategy_id BIGINT,
    flushed_at TIMESTAMPTZ NOT NULL,
    trigger_kind VARCHAR(10) NOT NULL,
    candidate_count INTEGER NOT NULL DEFAULT 0,
    released_count INTEGER NOT NULL DEFAULT 0,
    pushed_count INTEGER NOT NULL DEFAULT 0,
    short_count INTEGER NOT NULL DEFAULT 0,
    retried_count INTEGER NOT NULL DEFAULT 0,
    stalled_count INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_stream_batches_client_flushed ON stream_batches (client_id, flushed_at DESC);
